### ISSUE TITLE
폴더명이 한글일시 다운로드 도중 프로그램이 꺼집니다.

### ISSUE THREAD

**Issue by LittleTurtleNinger** [Creta5164/FlashPeeker#1]
폴더명이 영어라면 정상적으로 파일이 받아지나 한글일시엔 다운로드 바가 차지않으면서 멈춰버리고 프로그램이 튕깁니다.

**Comment by Creta5164** [comment]
현재 주전자닷컴 서버의 상태가 좋지 않은 것으로 확인됐습니다.
그래도 작업 수의 제한을 두는 업데이트를 진행하고 있습니다.

**Comment by Creta5164** [comment]
주전자닷컴의 서버의 상태가 좋지 않아 응답을 하지 않는 문제로 확인됐습니다.
이 예외는 현재 작업에 들어갔습니다.
