### ISSUE TITLE
파일명 금지 문자에 대해 처리하지 않으신 것 같습니다.

### ISSUE THREAD

**Issue by mir99712** [Creta5164/FlashPeeker#2]
현재 파일명으로 금지되는 문자가 있는 파일은 다운로드되지 않고 있습니다.
System.IO.Path.GetInvalidFileNameChars() 에 있는 문자는 다른 문자로 치환해야 합니다.

**Comment by mir99712** [comment]
테스트는 제 예전 작품으로 했습니다.
http://www.zuzunza.com/myflash/game_detail_writer.html?game_id=562146&category=1&writer=&menu=&cp=1&p=&y=&returnURL=/wroom.html?writer=mir99713

**Comment by Creta5164** [comment]
https://github.com/Creta5164/FlashPeeker/commit/afe6a1ef538aea28cbbdb2ef9dc84ed0f563731a 에서 수정됐습니다. 1.2버전으로 다운로드 해주세요!
